jobs:
  # track deployments on the environment
- deployment: DeploySimpleapp
  displayName: deploy Simple App
  pool:
    vmImage: 'Azure Pipelines'
  # creates an environment if it doesn't exist
  environment: 'simple-dev'
  