jobs:
- job:
  displayName: windows-latest
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - script: |
      call activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=%PYTHON_VERSION% numpy
    displayName: Install Anaconda packages

  - script: |
      call activate myEnvironment
      pip install pytest pytest-azurepipelines
      pytest
    displayName: pytest